// <auto-generated />
using System;
using Estacionamento.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamento.API.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20240710130355_MudaCamposNoModelPreco")]
    partial class MudaCamposNoModelPreco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Estacionamento.API.Models.Estacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HorarioChegada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HorarioSaida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoHora")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TempoCobrado")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorAPagar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estacionamentos");
                });

            modelBuilder.Entity("Estacionamento.API.Models.Preco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Precos");
                });
#pragma warning restore 612, 618
        }
    }
}
